name: Lab04 CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Chromium Browser
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install selenium
        python3 -m pip install webdriver_manager
        
    - name: Run Python Script
      run: |
        python3 ./Lab04/app.py